version: "3"
services:
    catalogdb:
        image: postgres
        container_name: catalogdb
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: CatalogDb
        volumes:
            - ./data:/var/lib/postgresql/data
        ports:
            - 5432:5432
    adminer:
        image: adminer
        container_name: adminer
        restart: always
        ports:
            - 8080:8080
        depends_on:
            - catalogdb
    catalogapi:
        image: catalogapi
        container_name: catalogapi
        restart: always
        build:
            context: .
            dockerfile: Services/Catalog/Catalog.Api/.DockerFile
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ConnectionStrings__DefaultConnection=Server=localhost;Port=5432;database=CatalogDb;uid=postgres;pwd=postgres;
        ports:
            - 5000:80
            - 5050:443
        depends_on:
            - catalogdb
